### ISSUE TITLE
Ren'Py 8.2.2 Android : AttributeError: 'org.renpy.android.PythonSDLActivity' object has no attribute 'armOnStop'

### ISSUE THREAD

**Issue by rex-nihilo** [renpy/renpy#5573]
With Ren'Py 8.2.2, when I build an Android version, everything is okay. But launching the app on Android crashes at the moment the interface is supposed to start, even with a new blank project.

Here is the traceback:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 283, in <module>
AttributeError: 'org.renpy.android.PythonSDLActivity' object has no attribute 'armOnStop'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 359, in bootstrap
  File "renpy/main.py", line 637, in main
  File "renpy/main.py", line 145, in run
  File "renpy/execution.py", line 955, in run_context
  File "00start.rpyc", line 279, in script
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "00start.rpyc", line 279, in script
  File "renpy/ast.py", line 823, in execute
  File "renpy/python.py", line 1178, in py_exec_bytecode
  File "renpy/common/00start.rpy", line 283, in <module>
  File "renpy/game.py", line 358, in call_in_new_context
  File "renpy/execution.py", line 955, in run_context
  File "_layout/screen_main_menu.rpymc", line 28, in script
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "_layout/screen_main_menu.rpymc", line 28, in script
  File "renpy/ast.py", line 823, in execute
  File "renpy/python.py", line 1178, in py_exec_bytecode
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
  File "renpy/ui.py", line 301, in interact
  File "renpy/display\core.py", line 2123, in interact
  File "renpy/display\core.py", line 983, in start
  File "renpy/display\core.py", line 1084, in post_init
AttributeError: 'org.renpy.android.PythonSDLActivity' object has no attribute 'armOnStop'

```

**Comment by renpytom** [comment]
So, this is a bad build. I'm going to fix it shortly, but for now you can grab the nightly fix build from https://nightly.renpy.org, and use that.

**Comment by rex-nihilo** [comment]
Yep! It works with version renpy-8.2.3.24061501+nightly-sdk
