### ISSUE TITLE
Error thrown on returning to Main Menu after Loading or starting a game.

### ISSUE THREAD

**Issue by colinharvie** [renpy/renpy#5879]
I'm not sure if this specifically is a bug as I have not yet identified where the problem is, but my game (which used to run fine in 8.2.3), now throws an error in 8.3 anytime the player tries returning to the main menu after loading or starting a game (whether that's from opening the menu and quitting to title, reaching the end of the game, or running code to return to the main menu from the console)

Specifically, this is the error:
```
While running game code:
  File "renpy/common/00start.rpy", line 296, in script
    python:
  File "renpy/common/00start.rpy", line 299, in <module>
    _enter_menu()
  File "renpy/common/00gamemenu.rpy", line 85, in _enter_menu
    renpy.take_screenshot((config.thumbnail_width, config.thumbnail_height))
AttributeError: 'NoneType' object has no attribute 'width'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 296, in script
    python:
  File "C:\RenPy\renpy-8.3.1-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\RenPy\renpy-8.3.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 299, in <module>
    _enter_menu()
  File "renpy/common/00gamemenu.rpy", line 85, in _enter_menu
    renpy.take_screenshot((config.thumbnail_width, config.thumbnail_height))
  File "C:\RenPy\renpy-8.3.1-sdk\renpy\exports\displayexports.py", line 596, in take_screenshot
    renpy.game.interface.take_screenshot(scale, background=background)
  File "C:\RenPy\renpy-8.3.1-sdk\renpy\display\core.py", line 1438, in take_screenshot
    surf = renpy.display.draw.screenshot(self.surftree)
  File "gl2draw.pyx", line 1218, in renpy.gl2.gl2draw.GL2Draw.screenshot
AttributeError: 'NoneType' object has no attribute 'width'
```

I noted that this is the same error as #5773 , although the trigger condition is different.

Note that this does NOT happen on the tutorial projects or a VERY old backup of this game.
I'm unsure if this is an actual error, or if something that was previously slipping by before 8.3 suddenly is now a problem.

I did some digging through the code, and though I couldn't find the CAUSE (I've looked through my code and enabled and disabled a lot, but to no success), I did find a way to prevent the error from happening:
Ensure that `_gl_test` is called in `label _start` in `00start.rpy` regardless of whether or not `restart` has a value (Line 211), and then in `00gltest.rpy` comment out the lines that cause it to return if restart has a value (line 307).

This essentially forces the `_gl_performance_test()` to run in `label _start` regardless of whether or not there is a value in `_restart`.

I don't know why this causes it to work, but it does, and I don't know why my game is causing the error to be thrown when the tutorial game is not. I will keep searching for this, but so far I've had no success. 

I did find out that the game works fine in the July 2nd nightly (renpy-8.3.0.24070111+nightly), but the error is thrown in the July 8th Nightly (renpy-8.3.0.24070802+nightly-sdk).

I'll keep looking for what specific part of my project is causing the problem to try and narrow it down, as my "solution" isn't ideal, and I would really like to use the features introduced in 8.3.

**Comment by renpytom** [comment]
Is this repeatable? If so, can you send me the game so I can see what's going on?

**Comment by Andykl** [comment]
We also had the same issue. If I understand correctly, the problem is that if you save the game before exit to main menu, but does not make explicit take_screenshot, it crashes with it.

**Comment by paranormalized-encryptid** [comment]
For what it's worth, I've been having exactly the same issue...

**Comment by colinharvie** [comment]
Just downloaded the latest nightly and tested out, this has fixed the issue for us! Thanks!
