### ISSUE TITLE
Struggling to get RPU updater working

### ISSUE THREAD

**Issue by WindChimesGames** [renpy/renpy#5322]
I'm fairly sure it's just me doing something wrong rather than a bug with the engine, but I couldn't find anyone with experience working with the new 8.2 RPU updater, so I hope it's okay if I post here. 

I'm trying to set up the 8.2 RPU updater to work with my game. My website is hosted at Hostinger, which is where I'm uploading the relevant .json / update files into a separate folder. However, I'm currently stuck at a couple of errors when I attempt to test updating from within the game. 

### Error 1
When trying to force an update (for testing) with force = True for the update.update function, it tells me "An error has occurred: could not verify update signature" 

### Error 2
If I try to use simulate = True instead on the update function, it gives me another error saying "AttributeError: 'Updater' object has no attribute 'pretty_version'"

The URL of the update function links to [DELETED LINK], which does seem to load fine and contain pretty_version when I access the URL directly in my web browser.

Any help would be very much appreciated. Thank you!

**Comment by renpytom** [comment]
Can you send me the game? Or a test game, so I can see what's going on? I want to make sure the key is included.

**Comment by WindChimesGames** [comment]
Sure! Is it okay if I PM you a download link in private on Discord? Or is there an email address you'd prefer me to send the files over to? Thank you for looking into this!

**Comment by lustfarmer** [comment]
I have same error when trying to update my game with 8.2 RPU.

**Comment by renpytom** [comment]
@WindChimesGames Discord's fine.

**Comment by danac78** [comment]
@renpytom Has this been resolved because I am getting the same errors despite following the documentation.

1. I add the build updates, it creates a PEM file.
2. Create a bucket in rd2 cloudflare, make it public, etc.
3. Build distribution and copy the three things to Cloudflare.
4. Add this:a 

```
 define url = "https://<useridredacted>.r2.cloudflarestorage.com/updates.json"
label splashscreen:
    $updater.update(url)
return
```

It launches The Question, Searches for Update, and Unable to verify the key.

Am I missing something?

[the_question.zip](https://github.com/renpy/renpy/files/15228338/the_question.zip)

Attached The question with those modifications.

**Comment by danac78** [comment]
I thought I changed it back to HTTPS in the define, but I didn't. But the same happens in both.

**Comment by renpytom** [comment]
Did you build the original game to include the update? Specifically, does update/key.pem exist?

**Comment by danac78** [comment]
Yes, in both Question and my Game.

**Comment by danac78** [comment]
Not sure if it is relevant, but when I try to access the json through web browser:
```

<Error>
<link type="text/css" rel="stylesheet" id="dark-mode-custom-link"/>
<link type="text/css" rel="stylesheet" id="dark-mode-general-link"/>
<style lang="en" type="text/css" id="dark-mode-custom-style"/>
<style lang="en" type="text/css" id="dark-mode-native-style"/>
<style lang="en" type="text/css" id="dark-mode-native-sheet"/>
<Code>InvalidArgument</Code>
<Message>Invalid Argument: Authorization</Message>
</Error>
```

**Comment by danac78** [comment]
Ok, I attached the bucket to a subdomain, so it definitely should be public access. So I will try in the morning.

**Comment by danac78** [comment]
@renpytom Nvm, I figured out the problem. I had to set it to a subdomain to make it public and list it correctly. Now, it is preparing to download fine (except that it doesn't match digest, but this was a quick test, so...).

**Comment by danac78** [comment]
Deleted and reuploaded the current to current. Now it says it is up to date. So, my problem is solved.

**Comment by renpytom** [comment]
Glad it worked. I'm closing this now.
