### ISSUE TITLE
Ren'Py deleting/resetting persistent data every time game launches.

### ISSUE THREAD

**Issue by RStar8** [renpy/renpy#5263]
I have couple of games in Steam. Recently the players started reporting an issue. Every time they launch the games their persistent data saved during last session (window size, preferences, gallery etc.) are getting reset. One of them sent this log to me and hopefully someone can help me understand what is going wrong here -
```
Thu Nov 30 21:45:44 2023
Windows-10-10.0.19041
Ren'Py 7.6.0.23051307
 
Bootstrap to the start of init.init. took 0.03s
Early init. took 0.00s
Loader init. took 0.01s
Loading error handling. took 0.03s
Loading script. took 1.27s
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading save slot metadata. took 0.01s
Loading persistent. took 0.00s
Faled to initialize steam: Exception(u'Init returned false.',)
Set script version to: (7, 6, 0)
Running init code. took 0.12s
Loading analysis data. took 0.02s
Analyze and compile ATL. took 0.03s
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Reloading save slot metadata. took 0.03s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache. took 0.00s
Making clean stores. took 0.00s
Initial gc. took 0.08s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object. took 0.11s
Cleaning stores took 0.00s
Init translation took 0.09s
Build styles took 0.00s
Load screen analysis took 0.01s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.04s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start. took 0.17s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: 'NVIDIA Corporation'
Renderer: 'NVIDIA GeForce RTX 4090/PCIe/SSE2'
Version: '4.6.0 NVIDIA 546.17'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1739, 978) drawable=(1739, 978)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096
controller: u'030000005e0400008e02000000007200' u'Xbox 360 Controller' 1L
controller: u'030000005e0400008e02000000007200' u'Xbox 360 Controller' 1L
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
Loading persistent.
Traceback (most recent call last):
  File "renpy/persistent.py", line 205, in load
    s = do.decompress(f.read())
error: Error -3 while decompressing: incorrect header check
```
I don't understand why this `incorrect header check` might be happening. Hopefully someone from here might be able to help because I asked in Ren'Py Discord and no one was able to help unfortunately. And another problem is none of us from the team is having this issue and we don't know how to reproduce.
As you can see the game is using Ren'Py 7.6.0. 

Any kind of help/guidence would be appriciated. Thank you.

**Comment by mal** [comment]
While it may or may not be related, you've previously mentioned that you're using a ["modified version of Ren'Py's Multipersistent save system"](https://github.com/renpy/renpy/issues/4725#issuecomment-1586237212). It would be useful to get more information on that to ensure we're not chasing an issue in your custom setup.

**Comment by renpytom** [comment]
It may also make sense to upgrade to 8.2.0 or  7.7.0, as it includes debugging for persistent data. 

What's happening here is that a corrupt persistent file is being produced, but it's not obvious why.

**Comment by RStar8** [comment]
> While it may or may not be related, you've previously mentioned that you're using a ["modified version of Ren'Py's Multipersistent save system"](https://github.com/renpy/renpy/issues/4725#issuecomment-1586237212). It would be useful to get more information on that to ensure we're not chasing an issue in your custom setup.

While this is true what I have tried is removing all the code related to the multipersistent system and the made a build using Ren'Py 7.6.2 and sent that build to the person that sent me the log and it didn't solve the issue.

What I will do next is, make a build using Ren'Py 8.2.0 and send the build to that person and hopefully get a log that makes more sense and post it back here. 

Thank you guys for responding.

**Comment by RStar8** [comment]
I tried launching the game using both Ren'Py 8.2.0 and 7.7.0, but in both cases at first when I clicked Launch Project it says Launching for couple of seconds and then returns to the main screen and the game doesn't launch. No logs updated no traceback generated in the game's folder as well.
Then if I launch any other project (which launches fine) and then try to launch the game (that people are having persistent issues), Ren'Py Luancher itself crashes. No logs updated no traceback generated in the game's folder again. This is the traceback from Ren'Py crashing -

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/project.rpy", line 785, in __call__
AttributeError: 'NoneType' object has no attribute 'update'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\main.py", line 635, in main
    run(restart)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\main.py", line 145, in run
    renpy.execution.run_context(True)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "launcher/game/front_page.rpyc", line 246, in script call
  File "launcher/game/front_page.rpyc", line 256, in script
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "launcher/game/front_page.rpyc", line 246, in script call
  File "launcher/game/front_page.rpyc", line 256, in script
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\ast.py", line 1968, in execute
    self.call("execute")
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\ast.py", line 1950, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\exports.py", line 3409, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\core.py", line 2150, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\core.py", line 3150, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\layout.py", line 1197, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\layout.py", line 1197, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\layout.py", line 1197, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\screen.py", line 793, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\layout.py", line 1197, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\behavior.py", line 1174, in event
    return handle_click(self.clicked)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\behavior.py", line 1095, in handle_click
    rv = run(action)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\behavior.py", line 395, in run
    return action(*args, **kwargs)
  File "game/project.rpy", line 785, in __call__
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\game.py", line 281, in invoke_in_new_context
    renpy.game.log.complete()
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\rollback.py", line 612, in complete
    delta = sd.get_changes(begin, self.current.stores.get(name, None))
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\python.py", line 173, in get_changes
    rv.update(previous)
AttributeError: 'NoneType' object has no attribute 'update'

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.0.24011301+nightly
Ren'Py Launcher 8.2.0.24011301+nightly
Sun Jan 14 12:39:55 2024
```

The game launches and works fine with Ren'Py 7.6.3, 8.1.3, 7.6.4 and 8.1.4
Same issue happens for both Ren'Py 7.7.0 and 8.2.0

**Comment by renpytom** [comment]
This is a (apparently recently introduced) bug in Ren'Py. I'm fixing it now.

**Comment by renpytom** [comment]
I just landed a fix. It's in c1f906fcbafb1e9e73158e7232f876ecd0c0de8a, and will be in the first  Ren'Py 8.2.0 prerelease when it comes out.

**Comment by RStar8** [comment]
I not 100% sure if it is supposed to work this way. I added the updated `python.py` from GitHub and replaced the original in renpy folder in my downloaded Ren'Py 8.2.0. It didn't solve the issue (the game still isn't launching) and I got a new crash log. I am posting is here if it helps -

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/project.rpy", line 785, in __call__
ValueError: not enough values to unpack (expected 2, got 1)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\main.py", line 635, in main
    run(restart)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\main.py", line 145, in run
    renpy.execution.run_context(True)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "launcher/game/front_page.rpyc", line 246, in script call
  File "launcher/game/front_page.rpyc", line 256, in script
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "launcher/game/front_page.rpyc", line 246, in script call
  File "launcher/game/front_page.rpyc", line 256, in script
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\ast.py", line 1968, in execute
    self.call("execute")
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\ast.py", line 1950, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\exports.py", line 3409, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\core.py", line 2153, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\core.py", line 3183, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\layout.py", line 1197, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\layout.py", line 1197, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\layout.py", line 1197, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\screen.py", line 793, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\layout.py", line 1197, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\behavior.py", line 1174, in event
    return handle_click(self.clicked)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\behavior.py", line 1095, in handle_click
    rv = run(action)
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\display\behavior.py", line 395, in run
    return action(*args, **kwargs)
  File "game/project.rpy", line 785, in __call__
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\game.py", line 281, in invoke_in_new_context
    renpy.game.log.complete()
  File "C:\Users\3D33P\Downloads\renpy-8-sdk\renpy\rollback.py", line 614, in complete
    self.current.stores[name], self.current.delta_ebc[name] = delta
ValueError: not enough values to unpack (expected 2, got 1)

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.0.24011402+nightly
Ren'Py Launcher 8.2.0.24011402+nightly
Mon Jan 15 16:08:16 2024
```

**Comment by RStar8** [comment]
I tried with Ren'Py `8.2.0.24011408+nightly`. Yes, it doesn't crash anymore. But the project still doesn't launch. Even the presplash image doesn't show up. No logs/traceback in either the project or the Ren'Py folder as well (which is most weird, I might be able  to check what is the issue if it crashed and gave me a traceback). Every other project launches and works fine.

**Comment by renpytom** [comment]
Sorry, is it your project that isn't launching in 8.2.0.24011408+nightly, and all others do? Since that's odd. Can you post the game files somewhere I can get at it (email is renpytom@gmail.com), so I can see if I can repeat the crash here?

**Comment by RStar8** [comment]
I have send a mail with the link to the project attached to it. Thanks a lot for doing this.

**Comment by renpytom** [comment]
Got it. 

Is that the persistent file that's causing the problem?

**Comment by RStar8** [comment]
Yes

**Comment by JaredOverfield** [comment]
I encountered a similar issue with persistent files resetting on every game startup. I was able to isolate the issue to a persistent list where I was adding all of my custom gallery image objects to. The persistent list is fine until it reaches a certain size (in this case 58 python objects) after which the persistent file is reset. I'm using Ren'Py v8.0.3. I'm going to run it through the latest nightly version to see what happens and if I can debug the issue.

**Comment by OsirianGames** [comment]
I encountered a similar issue with persistent files resetting on every game startup. I was able to isolate the issue to a persistent list where I was adding all of my custom gallery image objects to. The persistent list is fine until it reaches a certain size (in this case 58 python objects) after which the persistent file is reset. I'm using Ren'Py v8.0.3. I'm going to run it through the latest nightly version to see what happens and if I can debug the issue.

**Comment by RStar8** [comment]
This ceretainly helps. Unfortunately, I cannot launch the game using the latest nightly. Let's see if we can fix this issue first.

**Comment by renpytom** [comment]
@RStar8 , if you can't get the game launching in the current nightly, that's its own problem. Please file an issue so we can figure it out.

**Comment by RStar8** [comment]
The game is launching fine now with the Ren'Py 7.7.1 and I finally found someone who was having the issue of persistent getting deleted and was able to send a log genarated through the game built with Ren'Py 7.7.1. Here is the log file -
`
2024-04-02 19:44:38 UTC
Windows-10-10.0.22621
Ren'Py 7.7.1.24030407

Early init took 0.22s
Loading error handling took 0.21s
Loading script took 6.26s
Initializing save token:
Traceback (most recent call last):
  File "renpy/savetoken.py", line 333, in init
    init_tokens()
  File "renpy/savetoken.py", line 279, in init_tokens
    create_token(keys_fn)
  File "renpy/savetoken.py", line 213, in create_token
    with open(filename, "w") as f:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Dani\udcebl Thomassen\\AppData\\Roaming/RenPy/tokens\\security_keys.txt'
Traceback (most recent call last):
  File "renpy/savetoken.py", line 333, in init
    init_tokens()
  File "renpy/savetoken.py", line 279, in init_tokens
    create_token(keys_fn)
  File "renpy/savetoken.py", line 213, in create_token
    with open(filename, "w") as f:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Dani\udcebl Thomassen\\AppData\\Roaming/RenPy/tokens\\security_keys.txt'
Loading save slot metadata took 0.03s
Loading persistent took 0.00s
Initialized steam.
Set script version to: (7, 7, 1)
 - Init at renpy/common/00images.rpy:55 took 0.42581 s.
Running init code took 1.52s
Loading analysis data took 0.09s
Analyze and compile ATL took 0.06s
Reloading save slot metadata took 0.02s
Index archives took 0.00s
Dump and make backups took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.46s
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.24s
Cleaning stores took 0.00s
Init translation took 0.49s
Build styles took 0.01s
Load screen analysis took 0.04s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.14s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.01s
Interface start took 0.47s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 22.20.44.221025'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1739, 978) drawable=(1739, 978)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(1920, 1080) drawable=(1920, 1080)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096
`
There are no information about persistent load issues though. But I still posted it here just incase the issue with the save token has to do with something with this issue. Please let me know if the log is helpful and what I can do to fix this issue. 
Thanks.

**Comment by renpytom** [comment]
Upgrade to Ren'Py 8. It's an issue with the user's user directory not being representable in the system encoding. That's a problem in Python 2, but no longer a problem in Python 3. I don't think it's possible to fix this last traceback in Ren'Py 7. (Short of them renaming their user account.)
