### ISSUE TITLE
[Build issue] fatal error: pygame_sdl2/pygame_sdl2.h: No such file or directory

### ISSUE THREAD

**Issue by GiovanH** [renpy/renpy#6076]
After updating my dedicated ubuntu 22.04 laptop to the latest renpy revision, I can no longer build renpy:

```text
~/renpy > pushd pygame_sdl2
~/renpy/pygame_sdl2 ~/renpy

~/renpy/pygame_sdl2 > python setup.py install

running install
running bdist_egg
running egg_info
writing pygame_sdl2.egg-info/PKG-INFO
writing dependency_links to pygame_sdl2.egg-info/dependency_links.txt
writing top-level names to pygame_sdl2.egg-info/top_level.txt
reading manifest file 'pygame_sdl2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'gen/*.c'
warning: no files found matching 'gen/*.h'
adding license file 'COPYING.LGPL21'
adding license file 'COPYING.ZLIB'
writing manifest file 'pygame_sdl2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying src/pygame_sdl2/__init__.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/__init__.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/compat.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/threads/__init__.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2/threads
copying src/pygame_sdl2/threads/__init__.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2/threads
copying src/pygame_sdl2/threads/Py25Queue.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2/threads
copying src/pygame_sdl2/sprite.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/sysfont.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/time.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/version.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/version.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/sprite.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/time.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/sysfont.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/compat.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/__init__.py -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/DejaVuSans.ttf -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
copying src/pygame_sdl2/DejaVuSans.txt -> build/lib.linux-x86_64-cpython-310/pygame_sdl2
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/font.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/version.py -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/mouse.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/mixer.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/event.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/DejaVuSans.ttf -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/pygame_time.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/error.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/image.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
creating build/bdist.linux-x86_64/egg/pygame_sdl2/threads
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/threads/Py25Queue.py -> build/bdist.linux-x86_64/egg/pygame_sdl2/threads
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/threads/__init__.py -> build/bdist.linux-x86_64/egg/pygame_sdl2/threads
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/mixer_music.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/DejaVuSans.txt -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/sprite.py -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/surface.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/rwobject.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/time.py -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/render.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/power.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/sysfont.py -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/locals.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/joystick.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/compat.py -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/display.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/gfxdraw.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/scrap.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/controller.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/key.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/rect.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/transform.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/draw.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/color.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pygame_sdl2
copying build/lib.linux-x86_64-cpython-310/pygame_sdl2/__init__.py -> build/bdist.linux-x86_64/egg/pygame_sdl2
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/version.py to version.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/threads/Py25Queue.py to Py25Queue.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/threads/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/sprite.py to sprite.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/time.py to time.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/sysfont.py to sysfont.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/compat.py to compat.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/__init__.py to __init__.cpython-310.pyc
creating stub loader for pygame_sdl2/error.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/color.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/controller.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/rect.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/rwobject.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/surface.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/display.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/event.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/locals.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/key.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/mouse.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/joystick.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/power.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/pygame_time.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/image.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/transform.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/gfxdraw.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/draw.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/font.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/mixer.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/mixer_music.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/scrap.cpython-310-x86_64-linux-gnu.so
creating stub loader for pygame_sdl2/render.cpython-310-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/error.py to error.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/color.py to color.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/controller.py to controller.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/rect.py to rect.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/rwobject.py to rwobject.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/surface.py to surface.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/display.py to display.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/event.py to event.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/locals.py to locals.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/key.py to key.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/mouse.py to mouse.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/joystick.py to joystick.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/power.py to power.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/pygame_time.py to pygame_time.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/image.py to image.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/transform.py to transform.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/gfxdraw.py to gfxdraw.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/draw.py to draw.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/font.py to font.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/mixer.py to mixer.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/mixer_music.py to mixer_music.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/scrap.py to scrap.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygame_sdl2/render.py to render.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pygame_sdl2.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygame_sdl2.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygame_sdl2.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygame_sdl2.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygame_sdl2.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/pygame_sdl2-2.1.0-py3.10-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pygame_sdl2-2.1.0-py3.10-linux-x86_64.egg
removing '/home/gio/.virtualenvs/renpy/lib/python3.10/site-packages/pygame_sdl2-2.1.0-py3.10-linux-x86_64.egg' (and everything under it)
creating /home/gio/.virtualenvs/renpy/lib/python3.10/site-packages/pygame_sdl2-2.1.0-py3.10-linux-x86_64.egg
Extracting pygame_sdl2-2.1.0-py3.10-linux-x86_64.egg to /home/gio/.virtualenvs/renpy/lib/python3.10/site-packages
Adding pygame-sdl2 2.1.0 to easy-install.pth file

Installed /home/gio/.virtualenvs/renpy/lib/python3.10/site-packages/pygame_sdl2-2.1.0-py3.10-linux-x86_64.egg
Processing dependencies for pygame-sdl2==2.1.0
Finished processing dependencies for pygame-sdl2==2.1.0

~/renpy/pygame_sdl2 > python setup.py install_headers
running install_headers

~/renpy/pygame_sdl2 > popd
~/renpy
```

```text
~/renpy > python setup.py install

running install
running bdist_egg
running egg_info
writing renpy.egg-info/PKG-INFO
writing dependency_links to renpy.egg-info/dependency_links.txt
writing top-level names to renpy.egg-info/top_level.txt
reading manifest file 'renpy.egg-info/SOURCES.txt'
writing manifest file 'renpy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building '_renpy' extension
x86_64-linux-gnu-gcc -D_REENTRANT -I/usr/include/x86_64-linux-gnu -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/SDL2 -fPIC -Isrc -I/home/gio/.virtualenvs/renpy/include -I/usr/include/python3.10 -c src/IMG_savepng.c -o build/temp.linux-x86_64-cpython-310/src/IMG_savepng.o -std=gnu99 -Wno-unused-function
x86_64-linux-gnu-gcc -D_REENTRANT -I/usr/include/x86_64-linux-gnu -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/SDL2 -fPIC -Isrc -I/home/gio/.virtualenvs/renpy/include -I/usr/include/python3.10 -c src/core.c -o build/temp.linux-x86_64-cpython-310/src/core.o -std=gnu99 -Wno-unused-function
src/core.c:4:10: fatal error: pygame_sdl2/pygame_sdl2.h: No such file or directory
    4 | #include <pygame_sdl2/pygame_sdl2.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

Seems like something changed in the build process and an extra step is now required to properly install the header files, but I haven't been able to determine what it is. 

I see there seems to be a whole script for this at https://github.com/renpy/pygame_sdl2/blob/master/install_headers.py, but I don't see any instructions to run it as part of either the pygame_sdl2 project or the main renpy documentation.

**Comment by GiovanH** [comment]
I get this same error even after setting up an environment with the `prepare.sh` script in https://github.com/renpy/renpy-build,

**Comment by renpytom** [comment]
What version of Ren'Py are you trying to build?

**Comment by GiovanH** [comment]
This is the current `master` branch, so it should be 8.4.xxx

**Comment by GiovanH** [comment]
Trying to run a clean build with renpy-8.3.1.24090601 (the last version of pygame_sdl2 with a version tag) throws a different error during cython compilation of pygame_sdl2:

```text
pygame_sdl2.rwobject is out of date.

Error compiling Cython file:
------------------------------------------------------------
...
            sf.base = base
            sf.length = length
            sf.tell = 0

            rv = SDL_AllocRW()
            rv.size = subfile_size
                      ^
------------------------------------------------------------

src/pygame_sdl2/rwobject.pyx:453:22: Cannot assign type 'Sint64 (SDL_RWops *) except? -1 nogil' to 'Sint64 (*)(SDL_RWops *) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to the type of 'subfile_size'.
```

And the same sort of error compiling modules:

```text
renpy.text.hbfont is out of date.
- renpy.text.ftfont -----------------------------------------------------------
warning: include/freetype.pxd:16:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
warning: include/freetype.pxd:23:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310

Error compiling Cython file:
------------------------------------------------------------
...
        self.open_args.stream = &self.stream

        self.stream.size = size
        self.stream.pos = 0
        self.stream.descriptor.pointer = <void *> self
        self.stream.read = io_func
                           ^
------------------------------------------------------------

/home/gio/renpy/renpy/text/ftfont.pyx:215:27: Cannot assign type 'unsigned long (FT_Stream, unsigned long, unsigned char *, unsigned long) except? -1' to 'FT_Stream_IoFunc' (alias of 'unsigned long (*)(FT_Stream, unsigned long, unsigned char *, unsigned long) noexcept'). Exception values are incompatible. Suggest adding 'noexcept' to the type of 'io_func'.
```

The renpy virtualenv is using Cython version 3.0.11

**Comment by GiovanH** [comment]
I am seeing the same error running renpy-build `./prepare.sh`:

```text
...
In file included from gen3/pygame_sdl2.render.c:1227:
src/sdl_image_compat.h:11:21: warning: ‘mock_IMG_LoadSizedSVG_RW’ defined but not used [-Wunused-function]
   11 | static SDL_Surface *mock_IMG_LoadSizedSVG_RW(void) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~
warning: no files found matching 'gen/*.c'
warning: no files found matching 'gen/*.h'
renpy.display.render is out of date.
- renpy.display.render --------------------------------------------------------
src/core.c:4:10: fatal error: pygame_sdl2/pygame_sdl2.h: No such file or directory
    4 | #include <pygame_sdl2/pygame_sdl2.h>
      |          ^~~~~~~~~~~~~~~~~~~~
```

I do see that the renpy-build instructions specify Ubuntu 24, and I am currently running Ubuntu 22. I'll try a distribution update.

**Comment by GiovanH** [comment]
For reasons I *really thoroughly* do not understand, updating to Ubuntu 24 and doing a fresh clean build solved this problem.
