### ISSUE TITLE
Running on OpenBSD

### ISSUE THREAD

**Issue by cmyksoda** [renpy/renpy#7239]
It breaks the build on every platform where
SDL2's headers are not on the default include path — the BSDs, and likely
Homebrew/MacPorts layouts too.

### Symptom

Building Ren'Py 8.5.3 (tag `8.5.3.26051504`, commit `39895c1`) on
OpenBSD 7.9/amd64, clang 19.1.7:

```
building 'renpy.gl2.assimp' extension
c++ -pthread -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -pipe -g \
    -fPIC -Isrc -Itmp/gen3 -I/usr/local/include/python3.13 \
    -c src/assimpio.cc -o build/temp.../src/assimpio.o -Wno-unused-function
In file included from src/assimpio.cc:1:
src/assimpio.h:3:10: fatal error: 'SDL2/SDL.h' file not found
    3 | #include <SDL2/SDL.h>
      |          ^~~~~~~~~~~~
1 error generated.
error: command '/usr/bin/c++' failed with exit code 1
```

Every C module compiles fine. Compare the C command line, which has the
pkg-config includes, with the C++ one above, which has none:

```
cc -pthread -I/usr/local/include -I/usr/local/include/harfbuzz \
   -I/usr/X11R6/include/freetype2 -I/usr/local/include/fribidi \
   -I/usr/local/include/SDL2 -I/usr/X11R6/include -D_REENTRANT -fPIC ...
```

### Cause

`setup.py` derives the compiler flags from pkg-config, but only for C:

```python
env("CFLAGS",  f"pkg-config --cflags {pkgconfig_packages}")
env("LDFLAGS", f"pkg-config --libs {pkgconfig_packages}")
```

`CXXFLAGS` is never set. setuptools' `customize_compiler()` builds the C++
command line from a separate variable:

```python
cxxflags = cflags                                  # sysconfig CFLAGS
cflags   = os.environ.get('CFLAGS', cflags)        # env CFLAGS overrides
cxxflags = os.environ.get('CXXFLAGS', cxxflags)    # env CXXFLAGS overrides
cflags   = _add_flags(cflags, 'CPP')               # CPPFLAGS appended
cxxflags = _add_flags(cxxflags, 'CPP')             # CPPFLAGS appended
```

So `src/assimpio.cc` — the only C++ file in the tree — is compiled with
Python's stock sysconfig flags and none of the pkg-config include paths.

This is invisible on Linux because SDL2 installs to `/usr/include/SDL2`, so
`#include <SDL2/SDL.h>` resolves with no `-I` at all. On OpenBSD the headers are
in `/usr/local/include/SDL2`, which is not searched by default, so the include
fails.

### Fix

Mirror the existing pattern in `setup.py`:

```python
env("CXXFLAGS", f"pkg-config --cflags {pkgconfig_packages}")
```

That is consistent with how `CFLAGS` is already handled. Note it does replace
the sysconfig C++ flags (losing `-O2` etc., though `-fPIC` is appended
separately by distutils as `ccshared`) — exactly the same tradeoff `CFLAGS`
already makes.

A more conservative alternative is `CPPFLAGS`, which distutils *appends* to both
the C and C++ command lines rather than replacing, so it adds the include paths
while leaving the optimisation flags intact. That is what this port used:

```sh
CPPFLAGS=$(pkg-config --cflags assimp libavformat libavcodec libavutil \
  libswresample libswscale harfbuzz freetype2 fribidi sdl2)
export CPPFLAGS
```

With that set, the build completes with zero errors (62 extension modules), and
the engine runs: `lint` passes, and games render and play under both hardware GL
(Mesa Intel HD 6000, GL 4.6) and llvmpipe.

**Comment by renpytom** [comment]
This had been rewritten for Ren'Py 8.6 the master branch. Can you try it there?

**Comment by cmyksoda** [comment]
### Building:

This particular roadblock no longer requires a workaround for building on OpenBSD, but two new problems requiring user intervention have been introduced:

- `src/renpybidicore.c:3:10: fatal error: 'fribidi/fribidi.h' file not found`, another bug that has been in the codebase for a long time and invisible to Linux users.
- `src/ec_sign_core.c:28:10: fatal error: 'openssl/decoder.h' file not found` this is an OpenBSD specific problem because calling for `openssl` will always point to the included `libressl` package, even if openssl is installed.

I've included the working build script with the workarounds used to properly build on OpenBSD 7.9: [build-master2.sh](https://github.com/user-attachments/files/30883741/build-master2.sh)

### Regression from 8.5.3 performance on OpenBSD
- Sound is now entirely non-functioning
- Only around half of the games I have on this system launch (see [game_traceback.txt](https://github.com/user-attachments/files/30883748/game_traceback.txt), most of them had *very* similar errors to this)
- I am completely unable to open `preferences` in the launcher without it crashing (see [preferences_traceback.txt](https://github.com/user-attachments/files/30883751/preferences_traceback.txt))

**Comment by renpytom** [comment]
So, let me star off by pointing out that OpenBSD is not a supported platform, and so simply reporting regressions isn't going to get any work done - that's what not being supported means. "Sound is now entirely non-functioning" is not something actionable. 

What I can do is to is make changes to make things easier once the issues are identified. I've fixed the fribidi include. 

preferences_traceback.txt seems like it's an issue with freetype - it looks like the woff2 format isn't supported by your freetype. 

Loading from archives is not currently working - we're looking into why.

**Comment by cmyksoda** [comment]
Makes sense, I understand it isn't an officially supported OS, but it was once in ports and I'm hoping to help it return to ports eventually.

I definitely didn't mean to imply that these things should be a priority for y'all, I just wanted to point out the differences in the two builds on my machine in case they might be helpful for bettering compatibility in the future.

I'll try to dig into the sound thing more so I can provide more actionable feedback, but right now all I have is a suspicion that it's caused by the migration to SDL3 and the issues it could bring with sndio.

Thank you for fixing the fribidi include, I'll look into the freetype issues more when I'm able to get back to it.

**Comment by renpytom** [comment]
Of course, and I'm happy to accept/make reasonable compatibility changes. 

Ren'Py uses SDL3 for sound output. You'll also want to make your own game, rather than using someone else's - when another person's game is in use, sound errors are disabled.

**Comment by cmyksoda** [comment]
Okay, after debugging some more, most of this is either now fixed or was a product of my testing environment.

**1. Sound**

I've been testing this branch out of a private `$HOME` so that it couldn't mess with my main Ren'Py install. A byproduct of this meant that sndio was trying to authenticate with a newly generated cookie that it rejected. By simply copying my cookie from my main home directory into the sandbox, this was fixed. I was incorrect about the SDL3 correlation.

**2. Games not working**

#7255 fixed this. All six of the archived games on this machine now load their scripts cleanly where they previously died with `Could not load from archive`.

**3. Fonts - the thing that I would actually like you to work on, if you can**

You were right about it being WOFF2 support. OpenBSD's FreeType comes from the base system (xenocara), and it's built with `FT_CONFIG_OPTION_USE_BROTLI` commented out, so it links no brotli. There's no FreeType package in ports to install instead, so there's no WOFF2 support on OpenBSD at all, for any application — a newer FreeType wouldn't help.

Most of this I can fix downstream. Because the four `.ttf` names are aliased in `config.renamed_files`, a port can ship the `.ttf` originals and empty that directory. I've verified it: all four fonts load, which gets me into the preferences menu.

The only thing I can't fix myself is `renpy/common/_errorhandling.rpym:65`, which asks for the `.woff2` name directly and so isn't covered by `config.renamed_files`:

```python
style _default:
    # Text properties
    font "_WenQuanYiMicroHei.woff2"
```

In 8.5.3 that same line 65 read `font "DejaVuSans.ttf"`. `_WenQuanYiMicroHei` is the only one of the five bundled fonts with no `.ttf` alias in `config.renamed_files`, so it's the only one a port can't redirect, which means the error screen is the one screen I can't get a working font onto.

What I would like you to do:

1. Change that line to `font "_WenQuanYiMicroHei.ttf"`
2. Add `"_wenquanyimicrohei.ttf": "_wenquanyimicrohei.woff2"` to `config.renamed_files`

On every platform that has WOFF2 the loader redirects straight back to the same `.woff2` file, so behavior is unchanged and nothing new ships. It just makes the last font consistent with the other four, and it would let the port finish the job with no further upstream changes.

Thank you again for your help :)

**Comment by renpytom** [comment]
I don't think that's the right way to do this - config.renamed_files is for backwards compatibility, not for newly added files. I'd suggest either patching woff2 to .ttf as part of your build, or figuring out how to get the format working in OpenBSD, which would probably benefit everyone using the platform. 

At some point games will start shipping woff2 files - and so patching the engine is at best a band-aid, and I don't think that belongs in Ren'Py.

**Comment by cmyksoda** [comment]
That's fair enough. I'll keep `config.renamed_files` out of it and handle this downstream. Since WOFF2 is a lossless container around the same sfnt data, the port build can decompress the bundled fonts back to `.ttf` and patch the one `_errorhandling.rpym` reference, which is normal territory for an OpenBSD port.

No further upstream changes needed.

You're right that the proper fix is WOFF2 support in OpenBSD's FreeType itself, that lives in the base system rather than ports, so it's a conversation to have with the OpenBSD folks, and I'll look into raising it there eventually. As you say, games shipping their own WOFF2 fonts won't work until that happens regardless of what the engine does, so it's worth pursuing.

With the fribidi fix and #7255 in, everything I reported here is now either fixed on master or mine to handle downstream. Thank you for your help once again
