### ISSUE TITLE
7.4 for Windows unable to Launch Projects

### ISSUE THREAD

**Issue by rdurfee** [renpy/renpy#2243]
7.4.0.481 on Windows (nightly-2020-06-13-b0af3b31) is unable to launch projects. The game window never starts, but a traceback.txt is generated in the sdk folder.

```
I'm sorry, but an uncaught exception occurred.

Before loading the script.
WindowsError: [Error 267] The directory name is invalid: u'C:\\Development\\RenPyBeta\\renpy.py\\*.*'
```

[traceback.txt](https://github.com/renpy/renpy/files/4775248/traceback.txt)

**Comment by renpytom** [comment]
Can I have a longer traceback? And are you running this on a network drive?

**Comment by Belgerum** [comment]
I just had the same issue, got essentially the same traceback. This is all I get.
[traceback.txt](https://github.com/renpy/renpy/files/4775786/traceback.txt)
[log.txt](https://github.com/renpy/renpy/files/4775789/log.txt)

**Comment by rdurfee** [comment]
I attached the full trackback, but it's not very long. I am not running on a network drive, but on the laptop's built-in SSD from C:\Development\RenPyBeta.

This is the entire traceback.txt file:

`
I'm sorry, but an uncaught exception occurred.

Before loading the script.
WindowsError: [Error 267] The directory name is invalid: u'C:\\Development\\RenPyBeta\\renpy.py\\*.*'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Development\RenPyBeta/renpy/bootstrap.py", line 324, in bootstrap
    renpy.main.main()
  File "C:\Development\RenPyBeta/renpy/main.py", line 347, in main
    for fn in os.listdir(dir):
WindowsError: [Error 267] The directory name is invalid: u'C:\\Development\\RenPyBeta\\renpy.py\\*.*'
`

**Comment by Andykl** [comment]
I have found that launching launcher by bat file `lib\windows-i686\python.exe -OO renpy.py launcher` doesn't cause this. 
I traced it back to 7.3-7.4 inconsistencies:
7.3 - `sys.executable` is `C:\renpy\lib/windows-i686\renpy.exe`
7.4 via bat - `sys.executable` is `C:\renpy-git\lib\windows-i686\python.exe`
7.4 -  `sys.executable` is `C:\renpy-git\renpy.exe`
I'm not sure how exactly it's related.

**Comment by renpytom** [comment]
I'm going to be working on this today, but some issues with the Ren'Py build system are holding me back.

**Comment by Andykl** [comment]
I can launch projects by 6-15, so this problem fixed.

But I found another encoding problem. When launching project with console any print make
```
-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 10, in script call
    label start:
  File "renpy/common/00console.rpy", line 807, in script
    python in _console:
  File "renpy/ast.py", line 908, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2102, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00console.rpy", line 808, in <module>
    console.interact()
  File "renpy/common/00console.rpy", line 365, in interact
    self.run(lines)
  File "renpy/common/00console.rpy", line 481, in run
    traceback.print_exc()
  File "/home/tom/ab/nightly-build/tmp/install.linux-x86_64/lib/python2.7/traceback.py", line 233, in print_exc
  File "/home/tom/ab/nightly-build/tmp/install.linux-x86_64/lib/python2.7/traceback.py", line 124, in print_exception
  File "/home/tom/ab/nightly-build/tmp/install.linux-x86_64/lib/python2.7/traceback.py", line 13, in _print
  File "renpy/log.py", line 233, in write
    self.real_file.write(s)
LookupError: unknown encoding: cp866
```
If I start project itself - no encoding problems.

**Comment by renpytom** [comment]
I believe this has all been fixed.

**Comment by Belgerum** [comment]
On windows, I'm now able to launch projects, but they consistently crash with no log or traceback once the game reaches the main menu after the splashscreen.

**Comment by rdurfee** [comment]
I see the same issue as Belgerum (using the 6-19 build). Some projects work and some do not. The ones that crash, there is no traceback or log; the window simply closes.

**Comment by renpytom** [comment]
Is this still happening? If so, can I have a project that crashes?

**Comment by rdurfee** [comment]
Yes, it still crashes. It happens 100% of the time with the project I'm attaching, which is just an empty project I'd created a while ago with 7.3.

[TestHD.zip](https://github.com/renpy/renpy/files/4817118/TestHD.zip)

**Comment by Andykl** [comment]
I can start this project and create new project and start it as well by 06-27. @rdurfee and @Belgerum Can you check this issue again?

**Comment by Andykl** [comment]
Also, bug with console output also was fixed and works fine in all cases without encoding problems.

**Comment by rdurfee** [comment]
I downloaded the latest nightly and the attached project still doesn't work. When it closes, there's no log or traceback to say why. 3 of my 5 projects don't work, but the one that I'm working on now does, so I suppose it can be closed.

**Comment by Belgerum** [comment]
Same here. Some of my projects work, others crash just before the main menu. After some testing, it appears that the crash occurs sometime after `label splashscreen` runs, and before `label before_main_menu` runs, which I find somewhat odd.

**Comment by Belgerum** [comment]
Not sure if this is relevant, but attempting to run Lint on a build throws a `Launching the project failed` error, and generates the following traceback:

```I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "renpy/common/000statements.rpy", line 392, in lint_stop_generic
    renpy.error("channel %r is not defined" % channel)
TypeError: write() argument 1 must be unicode, not str

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 592, in main
    run(restart)
  File "renpy/main.py", line 108, in run
    if not renpy.arguments.post_init():
  File "renpy/arguments.py", line 288, in post_init
    return commands[command]()
  File "renpy/lint.py", line 792, in lint
    check_user(node)
  File "renpy/lint.py", line 397, in check_user
    node.call("lint")
  File "renpy/ast.py", line 1943, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 392, in lint_stop_generic
    renpy.error("channel %r is not defined" % channel)
  File "renpy/exports.py", line 2439, in error
    _error_handlers[-1](msg)
  File "renpy/lint.py", line 393, in error
    report("%s", msg)
  File "renpy/lint.py", line 65, in report
    print()
TypeError: write() argument 1 must be unicode, not str```

**Comment by rdurfee** [comment]
If I run Lint on the project I attached, I get a similar error, but it's complaining about an image, not a channel.

```
I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
TypeError: write() argument 1 must be unicode, not str

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 592, in main
    run(restart)
  File "renpy/main.py", line 108, in run
    if not renpy.arguments.post_init():
  File "renpy/arguments.py", line 288, in post_init
    return commands[command]()
  File "renpy/lint.py", line 762, in lint
    check_show(node, True)
  File "renpy/lint.py", line 354, in check_show
    image_exists(name, expression, tag, precise=precise)
  File "renpy/lint.py", line 280, in image_exists
    report("'%s' is not an image.", " ".join(name))
  File "renpy/lint.py", line 65, in report
    print()
TypeError: write() argument 1 must be unicode, not str
```

**Comment by Andykl** [comment]
It complain about first message to report. It's a bug where we try to push bytes (str) into text IO stream.
I think we should proofread all the cases where we do decode and delete where we don't need it.

**Comment by renpytom** [comment]
I haven't fixed this lint bug yet, but I did just fix a bug that was affecting Windows 32-bit, and since it was a hard crashing bug, it wouldn't create log entries or things like that. If everyone experiencing this could check out the 2020-06-29 nightly (or later) when it's out, I'd appreciate it - so far, I haven't been able to repeat things on my computer.

**Comment by Belgerum** [comment]
The 2020-06-29 build still crashes on reaching the main menu, but now generates a traceback:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 276, in script
    python:
  File "renpy/common/00start.rpy", line 276, in script
    python:
  File "renpy/common/00start.rpy", line 280, in <module>
    renpy.call_in_new_context("_main_menu")
AttributeError: 'NoneType' object has no attribute 'relative_volume'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 592, in main
    run(restart)
  File "renpy/main.py", line 147, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 276, in script
    python:
  File "renpy/common/00start.rpy", line 276, in script
    python:
  File "renpy/ast.py", line 908, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2102, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 280, in <module>
    renpy.call_in_new_context("_main_menu")
  File "renpy/game.py", line 333, in call_in_new_context
    return renpy.execution.run_context(False)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "renpy/ast.py", line 908, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2102, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 2866, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "renpy/display/core.py", line 3302, in interact_core
    renpy.audio.audio.interact()
  File "renpy/audio/audio.py", line 1154, in interact
    periodic()
  File "renpy/audio/audio.py", line 1107, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "renpy/audio/audio.py", line 1085, in periodic_thread_main
    periodic_pass()
  File "renpy/audio/audio.py", line 1027, in periodic_pass
    c.periodic()
  File "renpy/audio/audio.py", line 525, in periodic
    newq = QueueEntry(i, 0, False, True, topq.relative_volume)
AttributeError: 'NoneType' object has no attribute 'relative_volume'
```

**Comment by Andykl** [comment]
Belgerum's traceback was introduced in #2191 and fixed in #2262.

**Comment by Belgerum** [comment]
Seems so. The 06-30 nightly build seems to work perfectly with all of my projects.
